version: 1.0.{build}
image: Visual Studio 2019
install:
 - cinst codecov
configuration:
- Release
before_build:
- nuget restore
build:
  parallel: true
  verbosity: minimal
test_script:
 - dotnet test --collect:"XPlat Code Coverage" --no-build
after_test:
 - codecov -f "**/coverage.cobertura.xml"
skip_commits:
  files:
    - '**/*.md'
